### ISSUE TITLE
Access to retrofitApi variable in RetrofitClient

### ISSUE THREAD

**Issue by jkwiecien** [schibsted/account-sdk-android-web#7]
[`RetrofitClient`](https://github.com/schibsted/account-sdk-android-web/blob/master/webflows/src/main/java/com/schibsted/account/webflows/client/RetrofitClient.kt) class contains:
` private var retrofitApi: S? = null`

Does it really need to be private? Wouldn't private set be sufficient? There is a huge refactor because of the fact I can't access this instance directly anymore and rather use `suspend fun <V> makeAuthenticatedRequest(request: suspend (S) -> V?): V? `

**Comment by astrimagnussen** [comment]
available in 2.1.1 +
